
local function noise_expression(name, type)
  local expression = {
    type = "noise-expression",
    name = string.gsub(name, "-", "_"),
    expression = data.raw[type][name].autoplace.probability_expression
  }
  if data.raw[type][name].autoplace.local_expressions then
    expression.local_expressions = data.raw[type][name].autoplace.local_expressions
  end
  return expression
end

data:extend({
  -- START: Nauvis
  -- Nauvis tiles
  noise_expression("grass-1", "tile"),
  noise_expression("grass-2", "tile"),
  noise_expression("grass-3", "tile"),
  noise_expression("grass-4", "tile"),
  noise_expression("dry-dirt", "tile"),
  noise_expression("dirt-1", "tile"),
  noise_expression("dirt-2", "tile"),
  noise_expression("dirt-3", "tile"),
  noise_expression("dirt-4", "tile"),
  noise_expression("dirt-5", "tile"),
  noise_expression("dirt-6", "tile"),
  noise_expression("dirt-7", "tile"),
  noise_expression("sand-1", "tile"),
  noise_expression("sand-2", "tile"),
  noise_expression("sand-3", "tile"),
  noise_expression("red-desert-0", "tile"),
  noise_expression("red-desert-1", "tile"),
  noise_expression("red-desert-2", "tile"),
  noise_expression("red-desert-3", "tile"),
  noise_expression("water", "tile"),
  noise_expression("deepwater", "tile"),

  -- Nauvis decoratives
  noise_expression("big-rock", "simple-entity"),
  noise_expression("big-sand-rock", "simple-entity"),
  noise_expression("brown-asterisk", "optimized-decorative"),
  noise_expression("brown-asterisk-mini", "optimized-decorative"),
  noise_expression("brown-carpet-grass", "optimized-decorative"),
  noise_expression("brown-fluff", "optimized-decorative"),
  noise_expression("brown-fluff-dry", "optimized-decorative"),
  noise_expression("brown-hairy-grass", "optimized-decorative"),
  noise_expression("cracked-mud-decal", "optimized-decorative"),
  noise_expression("dark-mud-decal", "optimized-decorative"),
  -- noise_expression("enemy-decal", "optimized-decorative"),
  noise_expression("garballo", "optimized-decorative"),
  noise_expression("garballo-mini-dry", "optimized-decorative"),
  noise_expression("green-asterisk", "optimized-decorative"),
  noise_expression("green-asterisk-mini", "optimized-decorative"),
  noise_expression("green-bush-mini", "optimized-decorative"),
  noise_expression("green-carpet-grass", "optimized-decorative"),
  noise_expression("green-croton", "optimized-decorative"),
  noise_expression("green-desert-bush", "optimized-decorative"),
  noise_expression("green-hairy-grass", "optimized-decorative"),
  noise_expression("green-pita", "optimized-decorative"),
  noise_expression("green-pita-mini", "optimized-decorative"),
  noise_expression("green-small-grass", "optimized-decorative"),
  noise_expression("huge-rock", "simple-entity"),
  noise_expression("lichen-decal", "optimized-decorative"),
  noise_expression("light-mud-decal", "optimized-decorative"),
  noise_expression("medium-rock", "optimized-decorative"),
  noise_expression("medium-sand-rock", "optimized-decorative"),
  -- noise_expression("muddy-stump", "optimized-decorative"),
  -- noise_expression("nuclear-ground-patch", "optimized-decorative"),
  noise_expression("red-asterisk", "optimized-decorative"),
  noise_expression("red-croton", "optimized-decorative"),
  noise_expression("red-desert-bush", "optimized-decorative"),
  noise_expression("red-desert-decal", "optimized-decorative"),
  noise_expression("red-pita", "optimized-decorative"),
  noise_expression("sand-decal", "optimized-decorative"),
  noise_expression("sand-dune-decal", "optimized-decorative"),
  noise_expression("shroom-decal", "optimized-decorative"),
  noise_expression("small-rock", "optimized-decorative"),
  noise_expression("small-sand-rock", "optimized-decorative"),
  noise_expression("tiny-rock", "optimized-decorative"),
  noise_expression("white-desert-bush", "optimized-decorative"),
  -- noise_expression("worms-decal", "optimized-decorative"),
  -- END: Nauvis

  -- -- Vulcanus decoratives - Note, most already exist as noise layer under some other name
  -- noise_expression("vulcanus-chimney", "simple-entity"),
  -- noise_expression("vulcanus-chimney-faded", "simple-entity"),
  -- noise_expression("vulcanus-chimney-cold", "simple-entity"),
  -- noise_expression("vulcanus-chimney-short", "simple-entity"),
  -- noise_expression("vulcanus-chimney-truncated", "simple-entity"),
  -- noise_expression("huge-volcanic-rock", "simple-entity"),
  -- noise_expression("big-volcanic-rock", "simple-entity"),
  -- noise_expression("vulcanus-rock-decal-large", "optimized-decorative"),
  -- noise_expression("vulcanus-crack-decal", "optimized-decorative"),
  -- noise_expression("vulcanus-crack-decal-large", "optimized-decorative"),
  -- noise_expression("vulcanus-crack-decal-huge-warm", "optimized-decorative"),
  -- noise_expression("vulcanus-crack-decal-warm", "optimized-decorative"),
  -- noise_expression("calcite-stain", "optimized-decorative"),
  -- noise_expression("calcite-stain-small", "optimized-decorative"),
  -- noise_expression("sulfur-stain", "optimized-decorative"),
  -- noise_expression("sulfur-stain-small", "optimized-decorative"),
  -- noise_expression("sulfuric-acid-puddle", "optimized-decorative"),
  -- noise_expression("sulfuric-acid-puddle-small", "optimized-decorative"),
  -- noise_expression("crater-small", "optimized-decorative"),
  -- noise_expression("crater-large", "optimized-decorative"),
  -- noise_expression("pumice-relief-decal", "optimized-decorative"),
  -- noise_expression("vulcanus-sand-decal", "optimized-decorative"),
  -- noise_expression("vulcanus-dune-decal", "optimized-decorative"),
  -- noise_expression("waves-decal", "optimized-decorative"),
  -- noise_expression("medium-volcanic-rock", "optimized-decorative"),
  -- noise_expression("small-volcanic-rock", "optimized-decorative"),
  -- noise_expression("tiny-volcanic-rock", "optimized-decorative"),
  -- noise_expression("tiny-rock-cluster", "optimized-decorative"),
  -- noise_expression("small-sulfur-rock", "optimized-decorative"),
  -- noise_expression("tiny-sulfur-rock", "optimized-decorative"),
  -- noise_expression("sulfur-rock-cluster", "optimized-decorative"),
  -- noise_expression("vulcanus-lava-fire", "optimized-decorative"),

  -- START: Gleba
  -- Gleba tiles
  noise_expression("natural-yumako-soil", "tile"),
  noise_expression("natural-jellynut-soil", "tile"),
  noise_expression("wetland-yumako", "tile"),
  noise_expression("wetland-jellynut", "tile"),
  noise_expression("wetland-blue-slime", "tile"),
  noise_expression("wetland-light-green-slime", "tile"),
  noise_expression("wetland-green-slime", "tile"),
  noise_expression("wetland-light-dead-skin", "tile"),
  noise_expression("wetland-dead-skin", "tile"),
  noise_expression("wetland-pink-tentacle", "tile"),
  noise_expression("wetland-red-tentacle", "tile"),
  noise_expression("gleba-deep-lake", "tile"),
  noise_expression("lowland-brown-blubber", "tile"),
  noise_expression("lowland-olive-blubber", "tile"),
  noise_expression("lowland-olive-blubber-2", "tile"),
  noise_expression("lowland-olive-blubber-2", "tile"),
  noise_expression("lowland-pale-green", "tile"),
  noise_expression("lowland-cream-cauliflower", "tile"),
  noise_expression("lowland-cream-cauliflower-2", "tile"),
  noise_expression("lowland-dead-skin", "tile"),
  noise_expression("lowland-dead-skin-2", "tile"),
  noise_expression("lowland-cream-red", "tile"),
  noise_expression("lowland-red-vein", "tile"),
  noise_expression("lowland-red-vein-2", "tile"),
  noise_expression("lowland-red-vein-3", "tile"),
  noise_expression("lowland-red-vein-4", "tile"),
  noise_expression("lowland-red-vein-dead", "tile"),
  noise_expression("lowland-red-infection", "tile"),
  noise_expression("midland-turquoise-bark", "tile"),
  noise_expression("midland-turquoise-bark-2", "tile"),
  noise_expression("midland-cracked-lichen", "tile"),
  noise_expression("midland-cracked-lichen-dull", "tile"),
  noise_expression("midland-cracked-lichen-dark", "tile"),
  noise_expression("midland-yellow-crust", "tile"),
  noise_expression("midland-yellow-crust-2", "tile"),
  noise_expression("midland-yellow-crust-3", "tile"),
  noise_expression("midland-yellow-crust-4", "tile"),
  noise_expression("highland-dark-rock", "tile"),
  noise_expression("highland-dark-rock-2", "tile"),
  noise_expression("highland-yellow-rock", "tile"),
  noise_expression("pit-rock", "tile"),
  -- END: Gleba

})
